
#=====================================
#    Electromagnetic  processes
#=====================================

/gate/physics/addPhysicsList emlivermore

/gate/physics/Gamma/SetCutInRegion      world 1.0 mm
/gate/physics/Electron/SetCutInRegion   world 1.0 mm
/gate/physics/Positron/SetCutInRegion   world 1.0 mm

/gate/physics/Gamma/SetCutInRegion      patient 0.1 mm
/gate/physics/Electron/SetCutInRegion   patient 0.1 mm
/gate/physics/Positron/SetCutInRegion   patient 0.1 mm

/gate/physics/processList Enabled
/gate/physics/processList Initialized

/gate/physics/processes/PhotoElectric/setAugerElectron true

/gate/physics/displayCuts
