
#=====================================
#    Electromagnetic  processes
#=====================================

/gate/physics/addPhysicsList emstandard_opt3

/gate/physics/Gamma/SetCutInRegion      world 10.0 mm
/gate/physics/Electron/SetCutInRegion   world 10.0 mm
/gate/physics/Positron/SetCutInRegion   world 10.0 mm

/gate/physics/Gamma/SetCutInRegion      patient 0.1 mm
/gate/physics/Electron/SetCutInRegion   patient 0.1 mm
#/gate/physics/Positron/SetCutInRegion   patient 0.1 mm

/gate/physics/Gamma/SetCutInRegion      SPECThead 0.1 mm
/gate/physics/Electron/SetCutInRegion   SPECThead 0.1 mm

/gate/physics/processes/PhotoElectric/setAugerElectron true
/gate/physics/displayCuts
