# Generated by Django 2.0.4 on 2019-04-25 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CumActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('Organ', models.CharField(max_length=30)),
                ('t_1', models.FloatField(default=0.0, verbose_name='First time')),
                ('A_1', models.FloatField(default=0.0, verbose_name='First Activity')),
                ('t_2', models.FloatField(default=0.0, verbose_name='Second time')),
                ('A_2', models.FloatField(default=0.0, verbose_name='Second Activity')),
                ('t_3', models.FloatField(default=0.0, verbose_name='Third time')),
                ('A_3', models.FloatField(default=0.0, verbose_name='Third Activity')),
                ('t_4', models.FloatField(default=0.0, verbose_name='Fourth time')),
                ('A_4', models.FloatField(default=0.0, verbose_name='Fourth Activity')),
                ('CT_Patient', models.FileField(null=True, upload_to='../media/', verbose_name='Patient CT')),
                ('CT_Organ', models.FileField(null=True, upload_to='../media/', verbose_name='Source/target Organ')),
                ('CT_Target_1', models.FileField(blank=True, null=True, upload_to='../media/', verbose_name='Second Target Organ')),
                ('CT_Target_2', models.FileField(blank=True, null=True, upload_to='../media/', verbose_name='Third Target Organ')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('cumAct', models.FloatField(default=-10.0)),
                ('doseAbs', models.FloatField(default=-10.0)),
                ('location', models.CharField(blank=True, max_length=120, null=True)),
                ('category', models.CharField(blank=True, max_length=120, null=True)),
                ('nuclidechoice', models.CharField(choices=[('Lu', 'Lu-177'), ('I', 'I-131')], default='Lu', max_length=10)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
