# Generated by Django 2.0.4 on 2018-06-25 20:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('IRDoseApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cumactivity',
            name='A_1',
            field=models.FloatField(default=0.0, verbose_name='First Activity'),
        ),
        migrations.AddField(
            model_name='cumactivity',
            name='A_2',
            field=models.FloatField(default=0.0, verbose_name='Second Activity'),
        ),
        migrations.AddField(
            model_name='cumactivity',
            name='A_3',
            field=models.FloatField(default=0.0, verbose_name='Third Activity'),
        ),
        migrations.AddField(
            model_name='cumactivity',
            name='A_4',
            field=models.FloatField(default=0.0, verbose_name='Fourth Activity'),
        ),
        migrations.AddField(
            model_name='cumactivity',
            name='CT_Organ',
            field=models.FileField(blank=True, null=True, upload_to='../media/'),
        ),
        migrations.AddField(
            model_name='cumactivity',
            name='CT_Patient',
            field=models.FileField(blank=True, null=True, upload_to='../media/'),
        ),
        migrations.AddField(
            model_name='cumactivity',
            name='Organ',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='cumactivity',
            name='category',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='cumactivity',
            name='cumAct',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='cumactivity',
            name='doseAbs',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='cumactivity',
            name='location',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='cumactivity',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cumactivity',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cumactivity',
            name='t_1',
            field=models.FloatField(default=0.0, verbose_name='First time'),
        ),
        migrations.AddField(
            model_name='cumactivity',
            name='t_2',
            field=models.FloatField(default=0.0, verbose_name='Second time'),
        ),
        migrations.AddField(
            model_name='cumactivity',
            name='t_3',
            field=models.FloatField(default=0.0, verbose_name='Third time'),
        ),
        migrations.AddField(
            model_name='cumactivity',
            name='t_4',
            field=models.FloatField(default=0.0, verbose_name='Fourth time'),
        ),
        migrations.AddField(
            model_name='cumactivity',
            name='timeStamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cumactivity',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
