# Generated by Django 2.0.4 on 2018-06-25 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IRDoseApp', '0002_auto_20180625_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cumactivity',
            name='cumAct',
            field=models.FloatField(default=-10.0),
        ),
        migrations.AlterField(
            model_name='cumactivity',
            name='doseAbs',
            field=models.FloatField(default=-10.0),
        ),
    ]
