# Generated by Django 2.0.4 on 2018-06-28 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IRDoseApp', '0004_auto_20180627_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cumactivity',
            name='CT_Patient',
            field=models.FileField(blank=True, null=True, upload_to='../dosimetrie/stdGATE/data/', verbose_name='Patient CT'),
        ),
    ]
