# Generated by Django 2.0.4 on 2018-06-28 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IRDoseApp', '0005_auto_20180628_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cumactivity',
            name='CT_Patient',
            field=models.FileField(blank=True, null=True, upload_to='../data/', verbose_name='Patient CT'),
        ),
    ]
